# Generated by Django 5.0.6 on 2024-06-29 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_remove_orderitem_order_remove_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='resto.order'),
            preserve_default=False,
        ),
    ]
