# Generated by Django 5.0.6 on 2024-07-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0006_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Processing'), ('D', 'Delivered')], default='P', max_length=1),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
