# Generated by Django 5.0.6 on 2024-07-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0007_order_status_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
