# Generated by Django 5.0.6 on 2024-07-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0008_order_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
