# Generated by Django 5.0.6 on 2024-07-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0011_remove_order_quantity_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
