# Generated by Django 5.0.6 on 2024-07-03 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0017_menuitem_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Section Name', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resto.section'),
        ),
    ]
