# Generated by Django 5.0.6 on 2024-07-03 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0018_section_menuitem_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='resto.section'),
        ),
    ]
