# Generated by Django 5.0.6 on 2024-07-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0021_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='section_images/'),
        ),
    ]
