# Generated by Django 5.0.6 on 2024-07-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0022_section_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_end_time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_start_time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(),
        ),
    ]
