# Generated by Django 5.0.6 on 2024-07-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0024_cointransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earn', 'Earn'), ('redeem', 'Redeem')], max_length=10),
        ),
    ]
