# Generated by Django 5.0.6 on 2024-07-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0025_alter_cointransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointransaction',
            name='total_redeemed',
            field=models.IntegerField(default=0),
        ),
    ]
